// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        mavenCentral()
    }

    ext {
        kotlin_version = '2.1.21'
        google_services_version = '4.5.0'
        libVersions = [
                butterknife: '10.2.3',
                leakcanary: '1.5.1',
                mockito: '4.11.0',
                robolectric: '4.17'
        ]
        latestAboutLibsRelease='6.2.3@aar'
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.6.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.google.gms:google-services:$google_services_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}