/*
 *    Calendula - An assistant for personal medication management.
 *    Copyright (C) 2016 CITIUS - USC
 *
 *    Calendula is free software; you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation; either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with this software.  If not, see <http://www.gnu.org/licenses>.
 */

package es.usc.citius.servando.calendula.healthcareprovider.persistence;


import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.field.ForeignCollectionField;
import com.j256.ormlite.table.DatabaseTable;

import org.joda.time.DateTime;

import java.util.Collection;

import es.usc.citius.servando.calendula.drugdb.model.persistence.HomogeneousGroup;
import es.usc.citius.servando.calendula.drugdb.model.persistence.Prescription;
import es.usc.citius.servando.calendula.persistence.Patient;
import es.usc.citius.servando.calendula.persistence.typeSerializers.DateTimePersister;
import es.usc.citius.servando.calendula.healthcareprovider.model.ActiveMedVisualizationType;


/**
 * Persists active med items, whether they are DCPF codes or concrete meds (national codes).
 */
@DatabaseTable(tableName = "ActiveMedItems")
public class ActiveMedEntity {
    public static final String TABLENAME = "ActiveMedItems";
    public static final String COLUMN_ID = "_id";
    public static final String COLUMN_PATIENT = "Patient";
    public static final String COLUMN_TYPE = "Type";
    public static final String COLUMN_VISUALIZATION_TYPE = "VisualizationType";
    public static final String COLUMN_CODE = "Code";
    public static final String COLUMN_DEFAULT_DISPLAY = "DefaultDisplay";
    public static final String COLUMN_PRESCRIPTION = "Prescription";
    public static final String COLUMN_HOMOGENEOUS_GROUP = "HomogeneousGroup";
    public static final String COLUMN_DISPENSATION_INFO = "DispensationInfo";
    public static final String COLUMN_DOSAGE = "Dosage";
    public static final String COLUMN_VALIDITY_START = "ValidityStart";
    public static final String COLUMN_VALIDITY_END = "ValidityEnd";
    public static final String COLUMN_LAST_UPDATED = "LastUpdated";
    public static final String COLUMN_UPDATE_SEEN = "UpdateSeen";
    public static final String COLUMN_STATE = "State";


    /* Generic info */
    /**
     * Whether the last update has been seen or not by the user
     */
    @DatabaseField(columnName = COLUMN_UPDATE_SEEN)
    boolean updateSeen;
    /**
     * Autogenerated ID
     */
    @DatabaseField(columnName = COLUMN_ID, generatedId = true)
    private Long id;
    @NonNull
    @DatabaseField(columnName = COLUMN_PATIENT, foreign = true, foreignAutoRefresh = true)
    private Patient patient;
    /**
     * The active med type.
     *
     * @see ActiveMedType
     */
    @NonNull
    @DatabaseField(columnName = COLUMN_TYPE)
    private ActiveMedType type;
    /**
     * The active med visualization type.
     *
     * @see ActiveMedVisualizationType
     */
    @NonNull
    @DatabaseField(columnName = COLUMN_VISUALIZATION_TYPE)
    private ActiveMedVisualizationType visualizationType;/**
     * The code for this item (either DCPF or national code)
     */
    @NonNull
    @DatabaseField(columnName = COLUMN_CODE)
    private String code;
    /**
     * Default string to display if no extra med info is present
     */
    @NonNull
    @DatabaseField(columnName = COLUMN_DEFAULT_DISPLAY)
    private String defaultDisplay;
    /**
     * The associated {@link Prescription}, only if this is a national code item
     */
    @DatabaseField(columnName = COLUMN_PRESCRIPTION, foreign = true, foreignAutoRefresh = true)
    @Nullable
    private Prescription prescription = null;
    /**
     * The associated {@link HomogeneousGroup}, only if this is a dcpf item
     */
    @DatabaseField(columnName = COLUMN_HOMOGENEOUS_GROUP, foreign = true, foreignAutoRefresh = true)
    @Nullable
    private HomogeneousGroup homogeneousGroup = null;
    /* Dispensation info */
    @ForeignCollectionField(columnName = COLUMN_DISPENSATION_INFO)
    private Collection<DispensationInfoEntity> dispensationInfo;
    /**
     * The associated {@link DosageEntity}
     */
    @NonNull
    @DatabaseField(columnName = COLUMN_DOSAGE, foreign = true, foreignAutoRefresh = true, foreignAutoCreate = true)
    private DosageEntity dosage = null;
    /**
     * Start of validity period
     */
    @DatabaseField(columnName = COLUMN_VALIDITY_START, persisterClass = DateTimePersister.class)
    private DateTime validityStart;
    /**
     * End of validity period
     */
    @DatabaseField(columnName = COLUMN_VALIDITY_END, persisterClass = DateTimePersister.class)
    private DateTime validityEnd;
    /**
     * Date of the last update
     */
    @DatabaseField(columnName = COLUMN_LAST_UPDATED, persisterClass = DateTimePersister.class)
    private DateTime lastUpdated;

    /**
     * State of this active med. By default, {@link ActiveMedState#ACTIVE}
     */
    @DatabaseField(columnName = COLUMN_STATE)
    private ActiveMedState state = ActiveMedState.ACTIVE;

    public ActiveMedEntity() {
    }

    public ActiveMedEntity(Long id, @NonNull Patient patient, @NonNull ActiveMedType type, @NonNull ActiveMedVisualizationType visualizationType, @NonNull String code, @NonNull String defaultDisplay, Prescription prescription, HomogeneousGroup homogeneousGroup, Collection<DispensationInfoEntity> dispensationInfo, DateTime validityStart, DateTime validityEnd) {
        this.id = id;
        this.patient = patient;
        this.type = type;
        this.visualizationType = visualizationType;
        this.code = code;
        this.defaultDisplay = defaultDisplay;
        this.prescription = prescription;
        this.homogeneousGroup = homogeneousGroup;
        this.dispensationInfo = dispensationInfo;
        this.validityStart = validityStart;
        this.validityEnd = validityEnd;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NonNull
    public Patient getPatient() {
        return patient;
    }

    public void setPatient(@NonNull Patient patient) {
        this.patient = patient;
    }

    @NonNull
    public ActiveMedType getType() {
        return type;
    }

    public void setType(@NonNull ActiveMedType type) {
        this.type = type;
    }

    @NonNull
    public ActiveMedVisualizationType getVisualizationType() {
        return visualizationType;
    }

    public void setVisualizationType(@NonNull ActiveMedVisualizationType type) {
        this.visualizationType = type;
    }

    @NonNull
    public String getCode() {
        return code;
    }

    public void setCode(@NonNull String code) {
        this.code = code;
    }

    @NonNull
    public String getDefaultDisplay() {
        return defaultDisplay;
    }

    public void setDefaultDisplay(@NonNull String defaultDisplay) {
        this.defaultDisplay = defaultDisplay;
    }

    @Nullable
    public Prescription getPrescription() {
        return prescription;
    }

    public void setPrescription(@Nullable Prescription prescription) {
        this.prescription = prescription;
    }

    @Nullable
    public HomogeneousGroup getHomogeneousGroup() {
        return homogeneousGroup;
    }

    public void setHomogeneousGroup(@Nullable HomogeneousGroup homogeneousGroup) {
        this.homogeneousGroup = homogeneousGroup;
    }

    public Collection<DispensationInfoEntity> getDispensationInfo() {
        return dispensationInfo;
    }

    public void setDispensationInfo(Collection<DispensationInfoEntity> dispensationInfo) {
        this.dispensationInfo = dispensationInfo;
    }

    public DosageEntity getDosage() {
        return dosage;
    }

    public void setDosage(DosageEntity dosage) {
        this.dosage = dosage;
    }

    public DateTime getValidityStart() {
        return validityStart;
    }

    public void setValidityStart(DateTime validityStart) {
        this.validityStart = validityStart;
    }

    public DateTime getValidityEnd() {
        return validityEnd;
    }

    public void setValidityEnd(DateTime validityEnd) {
        this.validityEnd = validityEnd;
    }

    public DateTime getLastUpdated() {
        return lastUpdated;
    }

    public void setLastUpdated(DateTime lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    public void setLastUpdated(DateTime lastUpdated, boolean seen) {
        this.lastUpdated = lastUpdated;
        this.updateSeen = seen;
    }

    public boolean isUpdateSeen() {
        return updateSeen;
    }

    public void setUpdateSeen(boolean updateSeen) {
        this.updateSeen = updateSeen;
    }

    public ActiveMedState getState() {
        return state;
    }

    public void setState(ActiveMedState state) {
        this.state = state;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        ActiveMedEntity that = (ActiveMedEntity) o;

        if (type != that.type) {
            return false;
        }
        if (!code.equals(that.code)) {
            return false;
        }
        if ((dispensationInfo == null && that.dispensationInfo != null) || (dispensationInfo != null && that.dispensationInfo == null)) {
            return false;
        }
        if (dispensationInfo != null && that.dispensationInfo != null) {

            if (dispensationInfo.size() != that.dispensationInfo.size()) {
                return false;
            }
            if (!dispensationInfo.containsAll(that.dispensationInfo)) {
                return false;
            } else if (!that.dispensationInfo.containsAll(dispensationInfo)) {
                return false;
            }

        }
        if (!dosage.equals(that.dosage)) {
            return false;
        }
        if (validityStart != null ? !validityStart.equals(that.validityStart) : that.validityStart != null) {
            return false;
        }
        if (validityEnd != null ? !validityEnd.equals(that.validityEnd) : that.validityEnd != null) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int result = type.hashCode();
        result = 31 * result + code.hashCode();
        result = 31 * result + (dispensationInfo != null ? dispensationInfo.hashCode() : 0);
        result = 31 * result + dosage.hashCode();
        result = 31 * result + (validityStart != null ? validityStart.hashCode() : 0);
        result = 31 * result + (validityEnd != null ? validityEnd.hashCode() : 0);
        return result;
    }


    public enum ActiveMedState{
        ACTIVE, INACTIVE
    }

}
