package es.usc.citius.servando.calendula.healthcareprovider.persistence;

import androidx.annotation.Nullable;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.joda.time.DateTime;
import org.joda.time.Interval;
import org.joda.time.LocalDateTime;

import java.util.Comparator;

import es.usc.citius.servando.calendula.healthcareprovider.persistence.typeSerializers.IntervalPersister;
import es.usc.citius.servando.calendula.healthcareprovider.persistence.typeSerializers.LocalDateTimePersister;


@DatabaseTable(tableName = "ActiveMedDispensations")
public class DispensationInfoEntity {

    public static final String COLUMN_ID = "_id";
    public static final String COLUMN_DISPENSED = "Dispensed";
    public static final String COLUMN_DISPENSE_INTERVAL = "Interval";
    public static final String COLUMN_DISPENSED_CODE = "Code";
    public static final String COLUMN_DISPENSED_DATE = "DispensationDate";
    public static final String COLUMN_ACTIVE_MED = "ActiveMed";


    /* Generic info */

    /**
     * Autogenerated ID
     */
    @DatabaseField(columnName = COLUMN_ID, generatedId = true)
    private Long id;


    @DatabaseField(foreign = true, foreignAutoRefresh = true, columnName = COLUMN_ACTIVE_MED)
    private ActiveMedEntity activeMed;

    /**
     * <code>true</code> if the item has been dispensed, false otherwise
     */
    @DatabaseField(columnName = COLUMN_DISPENSED)
    private boolean dispensed = false;

    /**
     * Interval for dispensation
     */
    @DatabaseField(columnName = COLUMN_DISPENSE_INTERVAL, persisterClass = IntervalPersister.class)
    private Interval dispenseInterval;


    /**
     * Interval for dispensation
     */
    @DatabaseField(columnName = COLUMN_DISPENSED_DATE, persisterClass = LocalDateTimePersister.class)
    private LocalDateTime dispensedDateTime;


    /**
     * Code of the actual dispensed med, <code>null</code> if not dispensed yet.
     */
    @Nullable
    @DatabaseField(columnName = COLUMN_DISPENSED_CODE)
    private String dispensedCode;

    public DispensationInfoEntity() {
    }

    public DispensationInfoEntity(Long id, ActiveMedEntity activeMed, boolean dispensed, Interval dispenseInterval, LocalDateTime dispensedDateTime, String dispensedCode) {
        this.id = id;
        this.activeMed = activeMed;
        this.dispensed = dispensed;
        this.dispenseInterval = dispenseInterval;
        this.dispensedDateTime = dispensedDateTime;
        this.dispensedCode = dispensedCode;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public boolean isDispensed() {
        return dispensed;
    }

    public void setDispensed(boolean dispensed) {
        this.dispensed = dispensed;
    }

    public Interval getDispenseInterval() {
        return dispenseInterval;
    }

    public void setDispenseInterval(Interval dispenseInterval) {
        this.dispenseInterval = dispenseInterval;
    }

    @Nullable
    public String getDispensedCode() {
        return dispensedCode;
    }

    public void setDispensedCode(@Nullable String dispensedCode) {
        this.dispensedCode = dispensedCode;
    }

    public ActiveMedEntity getActiveMed() {
        return activeMed;
    }

    public void setActiveMed(ActiveMedEntity activeMed) {
        this.activeMed = activeMed;
    }

    public LocalDateTime getDispensedDateTime() {
        return dispensedDateTime;
    }

    public void setDispensedDateTime(LocalDateTime dispensedDateTime) {
        this.dispensedDateTime = dispensedDateTime;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;

        if (o == null || getClass() != o.getClass()) return false;

        DispensationInfoEntity that = (DispensationInfoEntity) o;

        return new EqualsBuilder()
                .append(dispensed, that.dispensed)
                .append(dispenseInterval, that.dispenseInterval)
                .append(dispensedDateTime, that.dispensedDateTime)
                .append(dispensedCode, that.dispensedCode)
                .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 37)
                .append(dispensed)
                .append(dispenseInterval)
                .append(dispensedDateTime)
                .append(dispensedCode)
                .toHashCode();
    }

    public static class DispensationEntityComparator implements Comparator<DispensationInfoEntity> {

        private static DispensationEntityComparator instance = null;

        private DispensationEntityComparator() {
        }

        public static DispensationEntityComparator getInstance() {
            if (instance == null) {
                instance = new DispensationEntityComparator();
            }
            return instance;
        }

        @Override
        public int compare(DispensationInfoEntity a, DispensationInfoEntity b) {
            final DateTime aStart = a.getDispenseInterval().getStart();
            final DateTime bStart = b.getDispenseInterval().getStart();
            return aStart.compareTo(bStart);
        }
    }
}
