/*
 *    Calendula - An assistant for personal medication management.
 *    Copyright (C) 2016 CITIUS - USC
 *
 *    Calendula is free software; you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation; either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with this software.  If not, see <http://www.gnu.org/licenses/>.
 */

package es.usc.citius.servando.calendula.healthcareprovider.persistence;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.hl7.fhir.dstu3.model.Timing;
import org.joda.time.LocalTime;

import es.usc.citius.servando.calendula.persistence.typeSerializers.LocalTimePersister;

/**
 *
 */
@DatabaseTable(tableName = "ActiveMedDosageEntry")
public class DosageEntryEntity {

    public static final String COLUMN_ID = "_id";
    public static final String COLUMN_DOSAGE = "Dosage";
    public static final String COLUMN_TEXT = "Text";
    public static final String COLUMN_REPEAT_TYPE = "RepeatType";
    public static final String COLUMN_REPEAT_VALUE = "RepeatValue";
    public static final String COLUMN_REPEAT_UNITS = "RepeatUnits";
    public static final String COLUMN_QUATITY_VALUE = "QuantityValue";
    public static final String COLUMN_QUATITY_UNITS = "QuantityUnits";
    public static final String COLUMN_TIME_OF_DAY = "TimeOfDay";
    public static final String COLUMN_PATIENT_INSTRUCTION = "PatInstruction";

    /* Generic info */

    /**
     * Autogenerated ID
     */
    @DatabaseField(columnName = COLUMN_ID, generatedId = true)
    private Long id;

    @DatabaseField(foreign = true, foreignAutoRefresh = true, columnName = COLUMN_DOSAGE)
    private DosageEntity dosage;

    @DatabaseField(columnName = COLUMN_TEXT)
    private String text;

    @DatabaseField(columnName = COLUMN_REPEAT_TYPE)
    private RepeatType repeatType;

    @DatabaseField(columnName = COLUMN_REPEAT_VALUE)
    private Double repeatValue;

    @DatabaseField(columnName = COLUMN_REPEAT_UNITS)
    private Timing.UnitsOfTime repeatUnits;

    @DatabaseField(columnName = COLUMN_QUATITY_VALUE)
    private Double quantityValue;

    @DatabaseField(columnName = COLUMN_QUATITY_UNITS)
    private String quantityUnits;

    @DatabaseField(columnName = COLUMN_TIME_OF_DAY, persisterClass = LocalTimePersister.class)
    private LocalTime at;

    @DatabaseField(columnName = COLUMN_PATIENT_INSTRUCTION)
    private String patientInstruction;


    public DosageEntryEntity() {
    }

    public DosageEntryEntity(DosageEntity dosage) {
        setDosage(dosage);
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getPatientInstruction() {
        return patientInstruction;
    }

    public void setPatientInstruction(String patientInstruction) {
        this.patientInstruction = patientInstruction;
    }

    public RepeatType getRepeatType() {
        return repeatType;
    }

    public void setRepeatType(RepeatType when) {
        this.repeatType = when;
    }

    public LocalTime getAt() {
        return at;
    }

    public void setAt(LocalTime at) {
        this.at = at;
    }

    public DosageEntity getDosage() {
        return dosage;
    }

    public void setDosage(DosageEntity dosage) {
        this.dosage = dosage;
    }

    public Double getRepeatValue() {
        return repeatValue;
    }

    public void setRepeatValue(Double repeatValue) {
        this.repeatValue = repeatValue;
    }

    public Timing.UnitsOfTime getRepeatUnits() {
        return repeatUnits;
    }

    public void setRepeatUnits(Timing.UnitsOfTime repeatUnits) {
        this.repeatUnits = repeatUnits;
    }

    public Double getQuantityValue() {
        return quantityValue;
    }

    public void setQuantityValue(Double quantityValue) {
        this.quantityValue = quantityValue;
    }

    public String getQuantityUnits() {
        return quantityUnits;
    }

    public void setQuantityUnits(String quantityUnits) {
        this.quantityUnits = quantityUnits;
    }

    @Override
    public String toString() {
        return "DosageEntryEntity{" +
                "id=" + id +
                ", text='" + text + '\'' +
                ", repeatType=" + repeatType +
                ", at=" + at +
                ", patientInstruction='" + patientInstruction + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;

        if (o == null || getClass() != o.getClass()) return false;

        DosageEntryEntity entity = (DosageEntryEntity) o;

        return new EqualsBuilder()
                .append(text, entity.text)
                .append(repeatType, entity.repeatType)
                .append(repeatValue, entity.repeatValue)
                .append(repeatUnits, entity.repeatUnits)
                .append(quantityValue, entity.quantityValue)
                .append(quantityUnits, entity.quantityUnits)
                .append(at, entity.at)
                .append(patientInstruction, entity.patientInstruction)
                .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 37)
                .append(text)
                .append(repeatType)
                .append(repeatValue)
                .append(repeatUnits)
                .append(quantityValue)
                .append(quantityUnits)
                .append(at)
                .append(patientInstruction)
                .toHashCode();
    }
}
