
package es.usc.citius.servando.calendula.drugdb.model.persistence;

import com.j256.ormlite.table.DatabaseTable;
import com.j256.ormlite.field.DatabaseField;

/**
*
* This class was generated automatically.
* Please check consistency and completion.
*/
@DatabaseTable(tableName = "ATCCode")
public class ATCCode{

	public static final String COLUMN_ID = "_id";
	public static final String COLUMN_ATC_CODE = "ATCCode";
	public static final String COLUMN_ATC_CODE_DESCRIPTION = "ATCCodeDescription";
	public static final String COLUMN_ATC_CODE_ID = "ATCCodeID";

	/**
	* Autogenerated ID
	*/
	@DatabaseField(columnName = COLUMN_ID, generatedId = true)
	private Long id;
	@DatabaseField(columnName = COLUMN_ATC_CODE)
	private String aTCCode;
	@DatabaseField(columnName = COLUMN_ATC_CODE_DESCRIPTION)
	private String aTCCodeDescription;
	@DatabaseField(columnName = COLUMN_ATC_CODE_ID)
	private String aTCCodeID;

	/**
	* Empty constructor, required by ORMLite
	*/
	public ATCCode(){}

	public ATCCode(String aTCCode, String aTCCodeDescription, String aTCCodeID){
		this.aTCCode = aTCCode;
		this.aTCCodeDescription = aTCCodeDescription;
		this.aTCCodeID = aTCCodeID;
	}

	public Long getId() { return id; }

	public void setId(Long id) { this.id = id; }

	public String getATCCode() { return aTCCode; }

	public void setATCCode(String aTCCode) { this.aTCCode = aTCCode; }

	public String getATCCodeDescription() { return aTCCodeDescription; }

	public void setATCCodeDescription(String aTCCodeDescription) { this.aTCCodeDescription = aTCCodeDescription; }

	public String getATCCodeID() { return aTCCodeID; }

	public void setATCCodeID(String aTCCodeID) { this.aTCCodeID = aTCCodeID; }


}
